### ISSUE TITLE
Lower right icon in web apps menu is not displaying

### ISSUE THREAD

**Issue by tristanpoland** [Gameplex-Software/gameplex-software.github.io#2]
The page at https://gameplex-software.github.io/apps/ has a broken image, it is most likely 404-ing.

Tested Browsers: Chrome, Firefox, Opera, Safari
Tested OS's: MacOS Big Sur, Android 11

**Comment by WilliamAnimate** [comment]
Add Windows 10 to the tested OS's, didnt report that. assumed you knew

**Comment by tristanpoland** [comment]
Issue resolved with minor patch
