### ISSUE TITLE
page header not loading on the form pages

### ISSUE THREAD

**Issue by tristanpoland** [Gameplex-Software/gameplex-software.github.io#3]
Requesing @WilliamAnimate take a quick look and see if he can debug it, thanks!

https://gameplex-software.github.io/request/service/
https://gameplex-software.github.io/join/

**Comment by WilliamAnimate** [comment]
will be on it in around 3:00 my time too lazy to find est psst abc dfg ok beback soon

**Comment by WilliamAnimate** [comment]
my class ended 2 mins early..
can you verify if the header is actually there? only the 'bar' for the header is there, but not the dropdowns/buttons

**Comment by tristanpoland** [comment]
Yes, the bar is there but the contents from header.html are not being loaded into the bar

**Comment by WilliamAnimate** [comment]
try a check: remove the google forms thing and see if the header appears, it may be blocking the header

**Comment by tristanpoland** [comment]
Looks like on my local test copy when I remove the form it still does not show up.

**Comment by tristanpoland** [comment]
Fixed issue, thanks for the help @WilliamAnimate
